package com.lemutugi.model.enums;

public enum EPrivilege {
    CREATE_USER, CREATE_ROLE, CREATE_PRIVILEGE, DELETE_USER, DELETE_ROLE, DELETE_PRIVILEGE, EDIT_USER, EDIT_ROLE, EDIT_PRIVILEGE, CREATE_ALL, DELETE_ALL, EDIT_ALL, LIST_ALL
}
